workflows:
  build-android:
    name: Build Zynix Android
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
